import { ToolItem } from "./types";

export const TOOLS: ToolItem[] = [
  // Compress & Resize
  {
    id: "compress-pdf",
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Kecilkan ukuran file PDF tanpa mengurangi kualitas teks (vektor tetap tajam).",
    category: "compress",
    isClientSide: true,
    icon: "Minimize2",
    popular: true,
  },
  {
    id: "resize-pdf-kb",
    slug: "resize-pdf-kb",
    name: "Resize PDF ke KB",
    description: "Sesuaikan ukuran PDF ke target kilobyte spesifik (misal: < 300 KB untuk portal upload).",
    category: "compress",
    isClientSide: true,
    icon: "Minimize2",
    popular: true,
  },
  {
    id: "resize-pdf-mb",
    slug: "resize-pdf-mb",
    name: "Resize PDF ke MB",
    description: "Atur batas maksimal ukuran file PDF dalam Megabyte (MB) dengan cepat.",
    category: "compress",
    isClientSide: true,
    icon: "Minimize2",
  },
  {
    id: "increase-pdf-size",
    slug: "increase-pdf-size",
    name: "Increase PDF Size",
    description: "Tambahkan ukuran file PDF untuk memenuhi syarat minimum upload portal.",
    category: "compress",
    isClientSide: true,
    icon: "Maximize2",
  },

  // Merge / Split / Organize
  {
    id: "merge-pdf",
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Gabungkan beberapa file PDF menjadi satu dokumen berurutan dengan drag and drop.",
    category: "organize",
    isClientSide: true,
    icon: "Layers",
    popular: true,
  },
  {
    id: "split-pdf",
    slug: "split-pdf",
    name: "Split PDF",
    description: "Pisahkan halaman PDF berdasarkan rentang (range) atau jadikan file zip per-halaman.",
    category: "organize",
    isClientSide: true,
    icon: "Scissors",
    popular: true,
  },
  {
    id: "rearrange-pdf",
    slug: "rearrange-pdf",
    name: "Rearrange Pages",
    description: "Atur ulang urutan halaman PDF secara visual dengan drag and drop thumbnail.",
    category: "organize",
    isClientSide: true,
    icon: "ArrowRightLeft",
  },
  {
    id: "delete-pages",
    slug: "delete-pages",
    name: "Delete Pages",
    description: "Pilih dan hapus halaman yang tidak diinginkan dari file PDF Anda.",
    category: "organize",
    isClientSide: true,
    icon: "Trash2",
  },
  {
    id: "extract-pages",
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Ekstrak halaman tertentu dari PDF menjadi file baru atau arsip ZIP terpisah.",
    category: "organize",
    isClientSide: true,
    icon: "Scissors",
  },
  {
    id: "rotate-pdf",
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Putar rotasi halaman PDF 90°, 180°, atau 270° per halaman atau semua sekaligus.",
    category: "organize",
    isClientSide: true,
    icon: "RotateCw",
    popular: true,
  },

  // Convert
  {
    id: "word-to-pdf",
    slug: "word-to-pdf",
    name: "Word ke PDF",
    description: "Konversi file DOC atau DOCX Microsoft Word menjadi dokumen PDF berformat rapi.",
    category: "convert",
    isClientSide: false,
    icon: "FileText",
    popular: true,
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    name: "PDF ke Word",
    description: "Konversi dokumen PDF kembali ke file Microsoft Word (DOCX) yang dapat diedit.",
    category: "convert",
    isClientSide: false,
    icon: "FileText",
    popular: true,
  },
  {
    id: "excel-to-pdf",
    slug: "excel-to-pdf",
    name: "Excel ke PDF",
    description: "Konversi spreadsheet Excel (XLS, XLSX) menjadi tabel PDF yang presisi.",
    category: "convert",
    isClientSide: false,
    icon: "FileSpreadsheet",
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    name: "PDF ke Excel",
    description: "Ekstrak tabel dan data angka dari PDF ke spreadsheet Excel (XLSX).",
    category: "convert",
    isClientSide: false,
    icon: "FileSpreadsheet",
  },
  {
    id: "ppt-to-pdf",
    slug: "ppt-to-pdf",
    name: "PowerPoint ke PDF",
    description: "Ubah slide presentasi PowerPoint (PPT, PPTX) menjadi dokumen PDF siap cetak.",
    category: "convert",
    isClientSide: false,
    icon: "FilePresentation",
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF ke JPG / PNG",
    description: "Render tiap halaman PDF menjadi gambar resolusi tinggi langsung di browser.",
    category: "convert",
    isClientSide: true,
    icon: "ImageIcon",
    popular: true,
  },

  // Edit
  {
    id: "edit-pdf",
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Tambahkan teks, gambar, coretan bebas, dan berbagai bentuk (shapes) ke PDF.",
    category: "edit",
    isClientSide: true,
    icon: "Edit3",
    popular: true,
  },
  {
    id: "watermark-pdf",
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Tambahkan teks atau logo gambar sebagai tanda air (watermark) diagonal/tile.",
    category: "edit",
    isClientSide: true,
    icon: "Stamp",
    popular: true,
  },
  {
    id: "add-page-number",
    slug: "add-page-number",
    name: "Add Page Number",
    description: "Sisipkan nomor halaman kustom (Header/Footer) dengan format fleksibel.",
    category: "edit",
    isClientSide: true,
    icon: "Hash",
  },
  {
    id: "add-image-to-pdf",
    slug: "add-image-to-pdf",
    name: "Add Image to PDF",
    description: "Sisipkan foto, tanda tangan, atau logo ke posisi mana pun di halaman PDF.",
    category: "edit",
    isClientSide: true,
    icon: "ImageIcon",
  },
  {
    id: "crop-pdf",
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Potong margin tepi halaman PDF secara presisi untuk menghemat ruang cetak.",
    category: "edit",
    isClientSide: true,
    icon: "Crop",
  },
  {
    id: "sign-pdf",
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Gambar tanda tangan, ketik nama dengan font kursif, atau upload tanda tangan.",
    category: "edit",
    isClientSide: true,
    icon: "PenTool",
    popular: true,
  },
  {
    id: "highlight-pdf",
    slug: "highlight-pdf",
    name: "Highlight PDF",
    description: "Beri warna stabilo / sorotan pada bagian teks atau area penting di PDF.",
    category: "edit",
    isClientSide: true,
    icon: "Highlighter",
  },
];
