export type ToolCategory = "Compress" | "Organize" | "Convert" | "Edit";

export interface ToolMetadata {
  slug: string;
  title: string;
  description: string;
  category: ToolCategory;
  icon: string;
  href: string;
  isClientSide: boolean;
  popular?: boolean;
}

export const TOOLS_LIST: ToolMetadata[] = [
  // 1. Compress
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Kecilkan ukuran file PDF tanpa mengurangi kualitas teks (vektor tetap tajam).",
    category: "Compress",
    icon: "Minimize2",
    href: "/tools/compress-pdf",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "compress-to-size",
    title: "Compress PDF ke Ukuran Kustom",
    description: "Kompres PDF ke ukuran target persis yang Anda inginkan (misal: < 100 KB, < 500 KB, < 1 MB atau input manual).",
    category: "Compress",
    icon: "Sliders",
    href: "/tools/compress-to-size",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "increase-pdf-size",
    title: "Increase PDF Size",
    description: "Tambahkan ukuran file PDF untuk memenuhi syarat minimum upload portal.",
    category: "Compress",
    icon: "Maximize2",
    href: "/tools/increase-pdf-size",
    isClientSide: true,
  },

  // 2. Organize
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    description: "Gabungkan beberapa file PDF menjadi satu dokumen berurutan dengan mudah.",
    category: "Organize",
    icon: "Layers",
    href: "/tools/merge-pdf",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    description: "Pisahkan halaman PDF berdasarkan rentang nomor halaman atau jadikan file ZIP per halaman.",
    category: "Organize",
    icon: "Scissors",
    href: "/tools/split-pdf",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "rearrange-pdf",
    title: "Rearrange Pages",
    description: "Atur ulang urutan halaman PDF secara visual dengan drag and drop thumbnail.",
    category: "Organize",
    icon: "ArrowRightLeft",
    href: "/tools/rearrange-pdf",
    isClientSide: true,
  },
  {
    slug: "delete-pages",
    title: "Delete Pages",
    description: "Pilih dan hapus halaman yang tidak diinginkan dari file PDF Anda.",
    category: "Organize",
    icon: "Trash2",
    href: "/tools/delete-pages",
    isClientSide: true,
  },
  {
    slug: "extract-pages",
    title: "Extract Pages",
    description: "Ekstrak halaman tertentu dari PDF menjadi file PDF baru atau arsip ZIP.",
    category: "Organize",
    icon: "Scissors",
    href: "/tools/extract-pages",
    isClientSide: true,
  },
  {
    slug: "rotate-pdf",
    title: "Rotate PDF",
    description: "Putar rotasi halaman PDF 90°, 180°, atau 270° per halaman atau semua sekaligus.",
    category: "Organize",
    icon: "RotateCw",
    href: "/tools/rotate-pdf",
    isClientSide: true,
    popular: true,
  },

  // 3. Convert
  {
    slug: "word-to-pdf",
    title: "Word ke PDF",
    description: "Konversi file DOC atau DOCX Microsoft Word menjadi dokumen PDF berformat rapi.",
    category: "Convert",
    icon: "FileText",
    href: "/tools/word-to-pdf",
    isClientSide: false,
    popular: true,
  },
  {
    slug: "pdf-to-word",
    title: "PDF ke Word",
    description: "Konversi dokumen PDF kembali ke file Microsoft Word (DOCX) yang dapat diedit.",
    category: "Convert",
    icon: "FileText",
    href: "/tools/pdf-to-word",
    isClientSide: false,
    popular: true,
  },
  {
    slug: "excel-to-pdf",
    title: "Excel ke PDF",
    description: "Konversi spreadsheet Excel (XLS, XLSX) menjadi tabel PDF yang presisi.",
    category: "Convert",
    icon: "FileSpreadsheet",
    href: "/tools/excel-to-pdf",
    isClientSide: false,
  },
  {
    slug: "pdf-to-excel",
    title: "PDF ke Excel",
    description: "Ekstrak tabel dan data angka dari PDF ke spreadsheet Excel (XLSX).",
    category: "Convert",
    icon: "FileSpreadsheet",
    href: "/tools/pdf-to-excel",
    isClientSide: false,
  },
  {
    slug: "ppt-to-pdf",
    title: "PowerPoint ke PDF",
    description: "Ubah slide presentasi PowerPoint (PPT, PPTX) menjadi dokumen PDF siap cetak.",
    category: "Convert",
    icon: "Presentation",
    href: "/tools/ppt-to-pdf",
    isClientSide: false,
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF ke JPG / PNG",
    description: "Render tiap halaman PDF menjadi gambar resolusi tinggi langsung di browser.",
    category: "Convert",
    icon: "Image",
    href: "/tools/pdf-to-jpg",
    isClientSide: true,
    popular: true,
  },

  // 4. Edit
  {
    slug: "edit-pdf",
    title: "Edit PDF",
    description: "Tambahkan teks, gambar, coretan bebas, dan bentuk (shapes) langsung ke dokumen PDF.",
    category: "Edit",
    icon: "Edit3",
    href: "/tools/edit-pdf",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "watermark-pdf",
    title: "Watermark PDF",
    description: "Tambahkan teks atau logo gambar sebagai tanda air (watermark) diagonal atau tile.",
    category: "Edit",
    icon: "Stamp",
    href: "/tools/watermark-pdf",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "add-page-number",
    title: "Add Page Number",
    description: "Sisipkan nomor halaman kustom (Header/Footer) dengan format fleksibel.",
    category: "Edit",
    icon: "Hash",
    href: "/tools/add-page-number",
    isClientSide: true,
  },
  {
    slug: "add-image-to-pdf",
    title: "Add Image to PDF",
    description: "Sisipkan foto, logo, atau stempel ke posisi mana pun di halaman PDF.",
    category: "Edit",
    icon: "Image",
    href: "/tools/add-image-to-pdf",
    isClientSide: true,
  },
  {
    slug: "crop-pdf",
    title: "Crop PDF",
    description: "Potong margin tepi halaman PDF secara presisi untuk menghemat ruang cetak.",
    category: "Edit",
    icon: "Crop",
    href: "/tools/crop-pdf",
    isClientSide: true,
  },
  {
    slug: "sign-pdf",
    title: "Sign PDF",
    description: "Gambar tanda tangan, ketik nama dengan font kursif, atau upload gambar tanda tangan.",
    category: "Edit",
    icon: "PenTool",
    href: "/tools/sign-pdf",
    isClientSide: true,
    popular: true,
  },
  {
    slug: "highlight-pdf",
    title: "Highlight PDF",
    description: "Beri warna stabilo / sorotan pada bagian teks atau area penting di PDF.",
    category: "Edit",
    icon: "Highlighter",
    href: "/tools/highlight-pdf",
    isClientSide: true,
  },
];
